---
title: "Are Community College Transfer Students Less Likely to Earn a Bachelor's Degree than Rising Four-year College Juniors?"
output: 
  beamer_presentation:
    theme: "CambridgeUS"
    colortheme: "dolphin"
author: "Patricia Martin & Xin Li"
date: "May, 2020"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

## Introduction

- Community college debate

    - Democratization vs. Diversion 

- Educational outcomes of transfer students (mixed results)  

    - Community college transfer students are less likely to complete a bachelor's degree
        - Doyle (2009)  
        - Long, B. T., & Kurlaender, M. (2009).  
    - Community college transfer students have similar graduation rates as students who started at a four-year institution.
        - Melguizo, Kienzl, & Alfonso (2011)
        - Xu, Jaggars, Fletcher, Fink (2018)

## Research question  

- Are Community College Transfer Students Less Likely to Earn a Bachelor’s Degree than students who started at a Four-year institution?

## Data

- National Education Longitudinal Study of 1988 [(NELS:88)](https://nces.ed.gov/surveys/nels88/)  

    - Nationally representative, longitudinal study of 8th graders in 1988.
    - A sample of students followed throughout secondary and postsecondary years. 

- Limitation: restricted data use file

    - Transcript-level data:
        - Number of non-remedial credits earned
        - Credits associated with threshold to identify transfer vs. rising junior
    - Regional data:
        - County-level labor market outcomes
        - Higher education characteristics (e.g. tuition by county)
  
## Data

The table below shows some descriptive statistics of the variables used in our project.  

### (insert Table 1 here)

## Empirical Strategy

### OLS & Probit

$$BA_i = Transfer_i \beta + X_i \gamma + \epsilon$$

- $BA_i$: Bachelor attainment, =1 if the student attained a bachelor’s degree within eight years of high school graduation. 

- $Transfer_i$: Transfer student, =1 for students who first attended a community college and transferred to a four-year college. 

- $X_i$: Individual-specific covariates:

    - Includes individual characteristics (sex, race/ethnicity, SES, etc.)
    - High school academic preparation and other characteristics (test scores, bachelor degree expectations, etc.)
    - Financial aid and work related activities (received grant, took out a loan, etc.)
    - Regional characteristics (region of college attended)

## Empirical Strategy

### OLS & Probit

### (insert Table 2 here)

## Empirical Strategy

### PSM

- Individuals might self-select into specific types of institutions based on many observed and unobserved individual characteristics.

- Matching groups of students based on observable pre-treatment characteristics to approximate randomization. 

- Based on strong assumption: all the factors related to college degree attainment were observed and all observed characteristics to match individuals are used in the estimation strategy.

- Propensity scores are estimated using all of the control variables in a probit function.

## Empirical Strategy

### PSM

### (insert PSM result here)

## Sensitivity analysis

Using sensitivity analysis, we can discuss the causal estimates posed by the authors, challenge their assumption of no unobserved confounding, and investigate how confounders might change the research conclusions.

## Sensitivity analysis

### Confounders

-  Non-random selection in college admission and applicant enrollment decision

    - Affect both institutional selection and academic performance

    - Including, but not limited to: individual ability, ambition, motivation, hard work, academic preparation, maturity, access to resources (e.g. school counselors), and family characteristics 
  
- The influence of institutional-level factors is confounded by the nonrandom selection of students into institutions with different qualities.

    - For example: Community college students who successfully transfer into a four-year college through the complicated transitional process between different education settings are strongly motivated and more inclined to persist (Lee, 1993; Wang, 2009). 
  
## Sensitivity analysis

### Benchmarking

Female and bachelor’s degree expectation are used as the benchmark variables to bound the relative strength of the unobserved confounders. These benchmark variables were chosen because they are strong and visible predictors of bachelor’s degree attainment theoretically and empirically (Melguizo et al, 2011; Wang, 2009), and likely explains more of the residual variation than any unobserved confounders.

## Sensitivity analysis

### Results

### (insert sensitivity analysis table here)

## Sensitivity analysis

### Results

### (insert sensitivity analysis plots here)

## Conclusion






